db: #MYSQL数据库配置
  port: 3306 #数据库端口
  user: root #数据库用户名
  password: 123456 #数据库密码
  dbname: aigc #数据库名称
  host: 127.0.0.1 #数据库地址
app: #本应用的一些配置
  port: 8000 #启动端口
  custom-load-front: false #如果为true，则会加载同级目录下的front目录的前端资源作为默认前端显示，否则使用应用内的前端资源
redis: #缓存配置
  host: 127.0.0.1 #reids地址
  port: 6379 #redis端口
  db: 1 #redos数据库
  password:  #redis密码，若没有密码，则为空
  pool-size: 0 #redis连接池大小，等于0时使用默认值，默认值为CPU数量*100（请注意此至和绘画队列数量一一对应，至少*2倍）